repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8


  # Run Prettier first
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, css, scss, json]
        additional_dependencies:
          - prettier@3.2.5

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.20.1"
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        entry: eslint
        language: node
        args: ["--fix"]  # Remove the --config argument
        additional_dependencies:
          - eslint@8.57.0
          - eslint-plugin-prettier@5.x
          - eslint-plugin-react-hooks@4.x
          - eslint-plugin-react-refresh@0.4.x
          - eslint-plugin-react@7.x
          - eslint-config-prettier@9.x
          - "@eslint/js"
