services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
      args:
        - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./backend/app:/app
      - ./backend:/code # Mount the entire backend directory for live code reloading
    env_file:
      - ./.env
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000" # Expose the backend service port for local access
    command:
      [
        "/app/entrypoint-local.sh",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
      - ./backend/.env
    ports:
      - "5432:5432" # Expose the database port for local access

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_DNS_URL=${BACKEND_URL}
        - VITE_BACKEND_PREFIX=${BACKEND_PREFIX}
    volumes:
      - ./frontend/app/src:/app/src # Mount the source directory for live code reloading
      - ./frontend/app/public:/app/public
    environment:
      - NODE_ENV=development
      - VITE_DNS_URL=${BACKEND_URL}
      - VITE_BACKEND_PREFIX=${BACKEND_PREFIX}
    command: yarn dev --host 0.0.0.0
    depends_on:
      - backend
    ports:
      - "3000:5173" # Expose the frontend service port for local access

  yarn-update:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend/app:/app
    command: yarn install

volumes:
  dev-db-data:
