# Generated by Django 4.2 on 2025-09-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, help_text='Email de contacto', max_length=254),
        ),
        migrations.AddField(
            model_name='provider',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales'),
        ),
    ]
