# Generated by Django 4.2 on 2025-09-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_provider_email_provider_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputprovider',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre este precio'),
        ),
    ]
