# Generated by Django 4.2 on 2025-09-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inputprovider_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='endproduct',
            name='base_cost_cop',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo base del producto en COP', max_digits=12),
        ),
    ]
