# Generated by Django 4.2 on 2025-09-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_endproduct_base_cost_cop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endproduct',
            name='additional_costs_cop',
        ),
        migrations.RemoveField(
            model_name='endproduct',
            name='base_cost_cop',
        ),
        migrations.DeleteModel(
            name='AdditionalCost',
        ),
    ]
