# Generated by Django 4.2 on 2025-09-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_base_cost_and_additional_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='provider_type',
        ),
    ]
