# Generated by Django 4.2 on 2025-09-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_type',
            field=models.CharField(choices=[('confection', 'Confección'), ('supply', 'Insumo'), ('fabric', 'Telas'), ('process', 'Procesos')], help_text='Tipo de insumo', max_length=20),
        ),
    ]
