name: Pre-commit Checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Set up Python environment.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Set up Node.js for ESLint and Prettier hooks.
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Cache pip dependencies (Backend Python).
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install Python dependencies from backend/requirements.txt
      - name: Install Python dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install pre-commit flake8 black isort

      # Run pre-commit checks
      - name: Run pre-commit checks on changed files
        run: |
          . .venv/bin/activate
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Changed files: $CHANGED_FILES"
          pre-commit run --files $CHANGED_FILES
